# Generated by Django 5.2.17 on 2026-10-09 15:11

import finance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0006_account_encrypted_text"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", finance_app.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
